In [2]:
import pandas as pd

In [65]:
df = pd.read_csv('data.csv', encoding='gb18030')

In [66]:
df.head()

comment  star
0  口味：不知道是我口高了，还是这家真不怎么样。 我感觉口味确实很一般很一般。上菜相当快，我敢说...     2
1                                 菜品丰富质量好，服务也不错！很喜欢！     4
2                        说真的，不晓得有人排队的理由，香精香精香精香精，拜拜！     2
3  菜量实惠，上菜还算比较快，疙瘩汤喝出了秋日的暖意，烧茄子吃出了大阪烧的味道，想吃土豆片也是口...     5
4  先说我算是娜娜家风荷园开业就一直在这里吃 每次出去回来总想吃一回 有时觉得外面的西式简餐总是...     4

In [67]:
df.shape

(2000, 2)

In [78]:
def make_label(df):
    df["sentiment"] = df["star"].apply(lambda x: 1 if x>3 else 0)

In [79]:
make_label(df)

pandas.core.frame.DataFrame

In [8]:
df.head()

comment  star  sentiment
0  口味：不知道是我口高了，还是这家真不怎么样。 我感觉口味确实很一般很一般。上菜相当快，我敢说...     2          0
1                                 菜品丰富质量好，服务也不错！很喜欢！     4          1
2                        说真的，不晓得有人排队的理由，香精香精香精香精，拜拜！     2          0
3  菜量实惠，上菜还算比较快，疙瘩汤喝出了秋日的暖意，烧茄子吃出了大阪烧的味道，想吃土豆片也是口...     5          1
4  先说我算是娜娜家风荷园开业就一直在这里吃 每次出去回来总想吃一回 有时觉得外面的西式简餐总是...     4          1

In [9]:
X = df[['comment']]
y = df.sentiment

In [10]:
X.shape

(2000, 1)

In [11]:
y.shape

(2000,)

In [12]:
X.head()

comment
0  口味：不知道是我口高了，还是这家真不怎么样。 我感觉口味确实很一般很一般。上菜相当快，我敢说...
1                                 菜品丰富质量好，服务也不错！很喜欢！
2                        说真的，不晓得有人排队的理由，香精香精香精香精，拜拜！
3  菜量实惠，上菜还算比较快，疙瘩汤喝出了秋日的暖意，烧茄子吃出了大阪烧的味道，想吃土豆片也是口...
4  先说我算是娜娜家风荷园开业就一直在这里吃 每次出去回来总想吃一回 有时觉得外面的西式简餐总是...

In [13]:
import jieba

In [14]:
def chinese_word_cut(mytext):
    return " ".join(jieba.cut(mytext))

In [16]:
X['cutted_comment'] = X.comment.apply(chinese_word_cut)

d:\program files\python37\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [17]:
X.cutted_comment[:5]

0    口味 ： 不 知道 是 我口 高 了 ， 还是 这家 真 不怎么样 。   我 感觉 口味 ...
1                        菜品 丰富 质量 好 ， 服务 也 不错 ！ 很 喜欢 ！
2           说真的 ， 不 晓得 有人 排队 的 理由 ， 香精 香精 香精 香精 ， 拜拜 ！
3    菜量 实惠 ， 上菜 还 算 比较 快 ， 疙瘩汤 喝出 了 秋日 的 暖意 ， 烧茄子 吃...
4    先说 我 算是 娜娜 家风 荷园 开业 就 一直 在 这里 吃   每次 出去 回来 总想 ...
Name: cutted_comment, dtype: object

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [23]:
X_train.shape

(1500, 2)

In [24]:
y_train.shape

(1500,)

In [25]:
X_test.shape

(500, 2)

In [26]:
y_test.shape

(500,)

In [27]:
def get_custom_stopwords(stop_words_file):
    with open(stop_words_file) as f:
        stopwords = f.read()
    stopwords_list = stopwords.split('\n')
    custom_stopwords_list = [i for i in stopwords_list]
    return custom_stopwords_list

In [28]:
stop_words_file = "stopwordsHIT.txt"
stopwords = get_custom_stopwords(stop_words_file)

In [29]:
stopwords[-10:]

['--', '』', '＝″', '【', '［＊］', '｝＞', '［⑤］］', '［①Ｄ］', 'ｃ］', 'ｎｇ']

In [30]:
from sklearn.feature_extraction.text import CountVectorizer

In [31]:
vect = CountVectorizer()

In [32]:
term_matrix = pd.DataFrame(vect.fit_transform(X_train.cutted_comment).toarray(), columns=vect.get_feature_names())

In [34]:
term_matrix.head()

00  01  10  100  11  12  120  12331  127  13  ...  鼎泰  鼎泰丰  鼎鼎有名  齐且  齐全  \
0   0   0   0    0   0   0    0      0    0   0  ...   0    0     0   0   0   
1   0   0   0    0   0   0    0      0    0   0  ...   0    0     0   0   0   
2   0   0   0    0   0   0    0      0    0   0  ...   0    0     0   0   0   
3   0   0   0    0   0   0    0      0    0   0  ...   0    0     0   0   0   
4   0   0   0    0   0   0    0      0    0   0  ...   0    0     0   0   0   

   齐刚  齐名  齐后  齐餐  龟速  
0   0   0   0   0   0  
1   0   0   0   0   0  
2   0   0   0   0   0  
3   0   0   0   0   0  
4   0   0   0   0   0  

[5 rows x 7305 columns]

In [35]:
term_matrix.shape

(1500, 7305)

In [36]:
vect = CountVectorizer(stop_words=frozenset(stopwords))

In [37]:
term_matrix = pd.DataFrame(vect.fit_transform(X_train.cutted_comment).toarray(), columns=vect.get_feature_names())

d:\program files\python37\lib\site-packages\sklearn\feature_extraction\text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['①ｄ'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


In [38]:
term_matrix.head()

00  01  10  100  11  12  120  12331  127  13  ...  鼎泰  鼎泰丰  鼎鼎有名  齐且  齐全  \
0   0   0   0    0   0   0    0      0    0   0  ...   0    0     0   0   0   
1   0   0   0    0   0   0    0      0    0   0  ...   0    0     0   0   0   
2   0   0   0    0   0   0    0      0    0   0  ...   0    0     0   0   0   
3   0   0   0    0   0   0    0      0    0   0  ...   0    0     0   0   0   
4   0   0   0    0   0   0    0      0    0   0  ...   0    0     0   0   0   

   齐刚  齐名  齐后  齐餐  龟速  
0   0   0   0   0   0  
1   0   0   0   0   0  
2   0   0   0   0   0  
3   0   0   0   0   0  
4   0   0   0   0   0  

[5 rows x 7304 columns]

In [39]:
max_df = 0.8 # 在超过这一比例的文档中出现的关键词（过于平凡），去除掉。
min_df = 3 # 在低于这一数量的文档中出现的关键词（过于独特），去除掉。

In [40]:
vect = CountVectorizer(max_df = max_df, 
                       min_df = min_df, 
                       token_pattern=u'(?u)\\b[^\\d\\W]\\w+\\b', 
                       stop_words=frozenset(stopwords))

In [41]:
term_matrix = pd.DataFrame(vect.fit_transform(X_train.cutted_comment).toarray(), columns=vect.get_feature_names())

d:\program files\python37\lib\site-packages\sklearn\feature_extraction\text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['①ｄ'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


In [42]:
term_matrix.head()

ipad  ok  ps  一下  一个  一个个  一个半  一个多  一些  一人  ...  麻将  麻烦  麻辣  麻酱  麻麻  黄瓜  \
0     0   0   0   0   0    0    0    0   0   0  ...   0   0   0   0   0   0   
1     0   0   0   0   0    0    0    0   0   0  ...   0   0   0   0   0   0   
2     0   0   0   0   0    0    0    0   0   0  ...   0   0   0   0   0   0   
3     0   0   0   0   0    0    0    0   0   0  ...   0   0   0   0   0   0   
4     0   0   0   0   0    0    0    0   0   0  ...   0   0   0   0   0   0   

   黄盖  黑椒  默默  齐全  
0   0   0   0   0  
1   0   0   0   0  
2   1   0   0   0  
3   0   0   0   0  
4   0   0   0   0  

[5 rows x 1972 columns]

In [43]:
#分类模型，采用朴素贝叶斯（Multinomial naive bayes）
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [44]:
from sklearn.pipeline import make_pipeline
pipe = make_pipeline(vect, nb)

In [45]:
#看看它都包含什么步骤
pipe.steps

[('countvectorizer',
  CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                  dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                  lowercase=True, max_df=0.8, max_features=None, min_df=3,
                  ngram_range=(1, 1), preprocessor=None,
                  stop_words=frozenset({'&', '*', '--', '.', './', '.一', ':',
                                        '~~~~', '———', '’', '”，', '℃', '→', '》），',
                                        '『', '』', '【', '一一', '）÷（１－', '）、', '＝″',
                                        '＝（', '［①Ｄ］', '［⑤］］', '［＊］', 'ｃ］', 'ｎｇ',
                                        '｝＞'}),
                  strip_accents=None, token_pattern='(?u)\\b[^\\d\\W]\\w+\\b',
                  tokenizer=None, vocabulary=None)),
 ('multinomialnb', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))]

In [47]:
#把未经特征向量化的训练集内容输入，做交叉验证，算出模型分类准确率的均值
from sklearn.model_selection import cross_val_score
cross_val_score(pipe, X_train.cutted_comment, y_train, cv=5, scoring='accuracy').mean()

d:\program files\python37\lib\site-packages\sklearn\feature_extraction\text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['①ｄ'] not in stop_words.
  'stop_words.' % sorted(inconsistent))
d:\program files\python37\lib\site-packages\sklearn\feature_extraction\text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['①ｄ'] not in stop_words.
  'stop_words.' % sorted(inconsistent))
d:\program files\python37\lib\site-packages\sklearn\feature_extraction\text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['①ｄ'] not in stop_words.
  'stop_words.' % sorted(inconsistent))
d:\program files\python37\lib\site-packages\sklearn\feature_extraction\text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated token

0.8333333333333334

In [48]:
#用训练集，把模型拟合出来
pipe.fit(X_train.cutted_comment, y_train)

Pipeline(memory=None,
         steps=[('countvectorizer',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=0.8,
                                 max_features=None, min_df=3,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=frozenset({'&', '*', '--', '.',
                                                       './', '.一', ':', '~~~~',
                                                       '———', '’', '”，', '℃',
                                                       '→', '》），', '『', '』',
                                                       '【', '一一', '）÷（１－', '）、',
                                                       '＝″', '＝（', '［①Ｄ］',
                                                       '［⑤］］', 

In [49]:
#在测试集上，对情感分类标记进行预测
pipe.predict(X_test.cutted_comment)

array([0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,

In [50]:
#先把预测结果保存
y_pred = pipe.predict(X_test.cutted_comment)

In [52]:
#读入 scikit-learn 的测量工具集
from sklearn import metrics

In [53]:
#看看测试准确率
metrics.accuracy_score(y_test, y_pred)

0.866

In [54]:
#对于分类问题，光看准确率有些不全面，咱们来看看混淆矩阵
metrics.confusion_matrix(y_test, y_pred)

array([[200,  37],
       [ 30, 233]], dtype=int64)

In [55]:
#与 SnowNLP 做个对比
from snownlp import SnowNLP
def get_sentiment(text):
    return SnowNLP(text).sentiments

In [56]:
y_pred_snownlp = X_test.comment.apply(get_sentiment)

In [57]:
y_pred_snownlp_normalized = y_pred_snownlp.apply(lambda x: 1 if x>0.5 else 0)

In [58]:
y_pred_snownlp_normalized[:5]

674     0
1699    1
1282    0
1315    0
1210    0
Name: comment, dtype: int64

In [59]:
metrics.accuracy_score(y_test, y_pred_snownlp_normalized)

0.77

In [60]:
metrics.confusion_matrix(y_test, y_pred_snownlp_normalized)

array([[189,  48],
       [ 67, 196]], dtype=int64)